#!/bin/sh

case "$1" in
prereqs)
    exit 0
    ;;
esac

. /scripts/functions

serial=$(tr '\0' '\n' < /proc/device-tree/serial-number)
if test -z "$serial"; then
    log_warning_msg 'Could not read serial number'
    exit 0
fi

if ! (set -o pipefail; printf '%s' "$serial" | sha256sum | awk '{ print substr($1, 1, 32) }' > "$rootmnt/etc/machine-id"); then
    log_warning_msg "Could not write $rootmnt/etc/machine-id"
    rm -f "$rootmnt/etc/machine-id"
    exit 0
fi

exit 0
